### ISSUE TITLE
Enable "edit visualization" button 

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#102]
The button is there, but it don't do nothin' :-1:

**Comment by Janekdererste** [comment]
I don't know if editing visualizations makes sense. Why not remove the one which is there and create a new one? Or in another way, what do you want to edit?

**Comment by billyc** [comment]
Let's say I put in the wrong projection, it would be nice to be able to just fix it.

**Comment by Janekdererste** [comment]
True
