### ISSUE TITLE
Create Project -- should have more fields

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#103]
Right now a project just has a name. We should add:

- Description (will show on info-strip if non-null)
- Contact info
- What else?

Maybe beyond the description, everything else should be user-definable key-value pairs as needed. I can imagine wanting web links, names of people, university affiliations... ?

**Comment by Janekdererste** [comment]
This would involve Adjustments on the backend first. We should think a little bit which fields we want for a project so that we don't have to change the database scheme too often
