### ISSUE TITLE
Allow user to stay logged in

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#106]
It's super annoying to have to re-login every time. No other website makes me do this.

**Comment by Janekdererste** [comment]
Auth tokens would have to be stored in LocalStorage instead of SessionStorage.

**Comment by Janekdererste** [comment]
Since we don't have a Server for our frontend we can't have refresh tokens. This means every time a token expires the user must re login. We could set the default session duration to 7days. Users would have to login every monday :-)
