### ISSUE TITLE
FileAPI calls frequently fail in multithreaded situations

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#109]
Calls to `FileAPI.downloadFile()` and `UploadStore().blah` often fail when called multiple times in close succession or in async/await situations.

Furthermore the failed calls often result in the reauthorize loop calling itself, so the page flashes away and comes back, which is a terrible UI experience.

I often get in situations where the main project page is just constantly refreshing itself in an endless loop. I have not figured out exactly how to trigger this behavior yet.

Steps to reproduce:
- Add a bunch of small files to the upload dialog and click upload. Some of them will fail.

Or:
- Upload a handful of PNG files to a model run, and try to open the dashboard (on branch `m0`). The reauth loop will usually begin. Note that if you just have ONE image file, it always works.

**Comment by Janekdererste** [comment]
Should be fixed by referenced pull request in the backend.
