### ISSUE TITLE
Visualizations should be taggable, and viz list filtered thusly

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#123]
- Create Viz wizard should allow (existing) tags to be chosen
- thumbnails should list tags
- visualizations should be filterable based on selected tag/model run

**Comment by Janekdererste** [comment]
Depends on https://github.com/matsim-org/viz-server/issues/87

**Comment by Janekdererste** [comment]
The Pull Request only solved a part of the issue. Reopening.
