### ISSUE TITLE
Point dev and prod deployment to prod backend

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz#124]

**Comment by billyc** [comment]
@Janekdererste  NOPE

Code all seemed to build OK but deplay failed.

See
https://travis-ci.com/matsim-org/viz/builds/107951002

```
dist/*: No such file or directory
Script failed with status 1
```

**Comment by billyc** [comment]
@Janekdererste it seems I can't auth on viz-dev.vsp.matsim.org this evening. 

```json
{"status":401,
 "internalErrorCode":"unauthorized",
 "message":"Client not found or redirect uri not valid"
}
```

**Comment by Janekdererste** [comment]
This is due for closing once the 'staging' url works

**Comment by Janekdererste** [comment]
staging url https://viz-staging.vsp.tu-berlin.de works
