### ISSUE TITLE
od-analysis ui nigglies

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#137]
**Scale slider**
* Scale slider is backwards (thinner is to the right). But we still want the starting point to be the far left. 
* Scale slider label is wrong on startup
* Ihab would like more stops on the scale slider

**Lines**
* Somehow mark the direction of the OD relations? Maybe by a small arrow symbol or something similar? Maybe an arrow symbol which only appears when you click on the OD line? Or at least an explanation?
* Popup labels could be more informative.

**Comment by nanddesai99** [comment]
> **Scale slider**
> 
> * Scale slider is backwards (thinner is to the right). But we still want the starting point to be the far left.
> * Scale slider label is wrong on startup
> * Ihab would like more stops on the scale slider
> 
> **Lines**
> 
> * Somehow mark the direction of the OD relations? Maybe by a small arrow symbol or something similar? Maybe an arrow symbol which only appears when you click on the OD line? Or at least an explanation?
> * Popup labels could be more informative.

**Comment by nanddesai99** [comment]
Scale slider bug fixed«

**New**

- Circles with numbers don't change size.
- Legend for differentiating scale size

**Comment by nanddesai99** [comment]
Legend for differentiating scale size is completed.

**Comment by nanddesai99** [comment]
Circles with numbers change size when clicking origin or destination.

**Comment by nanddesai99** [comment]
There is a scaling factor, you can add while setting up the aggregate o/d map. Scaling factor runs as intended.
