### ISSUE TITLE
Which browsers should be supported?

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz#29]
Currently @billyc and me are developing in chrome. Occasionally I am testing the application on Firefox. Trying the app on Microsoft-Edge showed some issues with login and the the flows visualization. 

Should we support other browsers than Chrome and Firefox? http://gs.statcounter.com/browser-market-share/desktop/worldwide indicates we should support Safari and Edge too. (I am unwilling to support IE).

**Comment by kainagel** [comment]
I think that for the time being we are writing research/demo code.  Both Chrome and Firefox are available on all the systems that we have.  So I don't think that there is a need to support more than those two (or, if that simplifies things, only one of them).

**Comment by billyc** [comment]
OK. Given Kai's answer, let's build & test with Chrome + Firefox.
