### ISSUE TITLE
Do we need the docs/code structure?

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz#3]
This seems to freak out IDEs and their git clients if one opens a project in a subdirectory. Also, the .gitignore file in the code folder is not respected. All settings from there would have to be copied to <root>/.gitignore.

I guess this structure was created for setting up github pages? Maybe a gh-pages branch works better?

**Comment by Janekdererste** [comment]
Will be fixed by #9

**Comment by billyc** [comment]
Fixed
