### ISSUE TITLE
Make demo visualizations use input files from file server

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz#36]
* remove hard coded usage of demo files
* get input parameters into visualization type depends on https://github.com/matsim-org/viz-server/issues/28
* implement fetching of files from the file server

**Comment by billyc** [comment]
@Janekdererste  -- here you go

### Network Flow Viz
- geojson file input
- variable containing link demand
- variable containing link capacity
- scale factor (default 100)

### Accessibilities
- geojson file input
- configuration YML file input

Note for the accessibilities viz, all of the configuration is currently in a YML file. The shortest path to completion is to just upload that file; but a true UI would instead have all of those parameters included. Let's do the former, for now, and think about how to "genericize" this later.
