### ISSUE TITLE
Info + Delete Button on each Viz in the Visualizations overview

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-org/viz#51]
Some ideas:

Currently all visualizations have only a placeholder text. It would be nice to have an Info button that is always there / appears while hoovering with the mouse other the Viz tile that shows

1. - name of visualization (to be set by the user, e.g. "run 123 with transit and flowCapacity 0.12")
2. - (maybe name of the visualization type)
3. - input files used
4. - settings

Maybe as a new window where all these settings/files can be replaced.

An delete button (opens small window to confirm delete) would also be nice.

Maybe just put both on top of the viz tile (on the right-most third of the tile).

**Comment by billyc** [comment]
main issue fixed; moving Gregor's additional suggestions to a new issue #121
