### ISSUE TITLE
Viz thumbnails must auto-generate, or at least be type-specific

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-org/viz#52]
(while having set up different Visualizations using different Schedules)

While looking longer on it, it seems it could even be a mix of several different schedules displayed all at the same time on the same Viz tile instead of one schedule per Viz tile as set up in the "Add Viz" dialog.

**Comment by billyc** [comment]
Yes the thumbnail is currently just a placeholder image -- it does not represent your actual visualization. When I get around to fixing this: 
- https://github.com/mapbox/mapbox-gl-js/issues/6448
- https://stackoverflow.com/questions/20958078/resize-a-base-64-image-in-javascript-without-using-canvas

**Comment by billyc** [comment]
- added title and viz-id to the thumbnail so you can tell them apart, while waiting for the thumbnail code to land

**Comment by billyc** [comment]
- Phase 1 will have a thumbnail representing the viz type
- After we can save thumbnails in the database, I will attack the thumbnail/snapshotting idea

**Comment by billyc** [comment]
I removed thumbnails entirely, for now, so this issue can be delayed post-M1.
