### ISSUE TITLE
Pick an acceptable font

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#75]
**Montserrat** is very pretty in regular but IMHO is far too thick in bold for our headings.

For now, I've switched to **Raleway** which is similarly round, which I love, but has more open space in the closed letters such as 'a' and 'e'.  That should make it more readable in small sizes.

Also it has a really distinctive 'w' which I love.

For discussion.

**Raleway:**
- https://fonts.google.com/specimen/Raleway

**Comment by Janekdererste** [comment]
How about open sans https://fonts.google.com/specimen/Open+Sans? 
Raleway seems to be a little thin, which makes it grainy on low res screens. (I have one :-)) It is a little less playfull, what I like.
