### ISSUE TITLE
Private projects are being shown on Start Page

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz#76]
All projects and viz seem to be showing up on the Start Page, regardless of whether the project is marked as "public" or "private".

**Comment by Janekdererste** [comment]
This is related to https://github.com/matsim-org/viz-server/issues/64

**Comment by Janekdererste** [comment]
Question is, should the start page only show public projects? Start Page and Projects Page both query the same endpoint at the moment. If the Projects Page goes away eventually, it would make sense to show public and private projects on the StartPage if the user is logged in and only public ones when not.

If we keep things separated it could also make sense to only show public projects on the start page and only personal ones in the project page

**Comment by billyc** [comment]
Ah, this already exists. I proposed a change to the FileAPI in #97 such that you can separate requests for public visualizations from requests for "my" projects. I don't think one API call should do both things, do you?

This looks worse now in the UI, because I'm merging the Projects page and the Start page. See #98

**Comment by billyc** [comment]
See #97

**Comment by Janekdererste** [comment]
This is no longer true. There is no public projects section right now
